name: kids_preschool
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.8
  flutter_tts: ^3.3.3
  sqflite: ^2.0.2
  rate_my_app: ^1.1.2
  audioplayers: ^0.20.1
  url_launcher: ^6.0.20
  auto_size_text: ^3.0.0
  share_plus: ^3.1.0
  floodfill_image: ^0.0.8
  google_mobile_ads: ^1.1.0
  app_tracking_transparency: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/database/
    - assets/icons/
    - assets/images/
    - assets/background/
    - assets/category/
    - assets/animation/
    - assets/time/
    - assets/sounds/
    - assets/animals/
    - assets/birds/
    - assets/education/
    - assets/fruits/
    - assets/money/
    - assets/shapes/
    - assets/vehicles/
    - assets/months/
    - assets/days/
    - assets/numbers/
    - assets/alphabets/
    - assets/alphabets_objects/
    - assets/colours/
    - assets/upper/
    - assets/lower/
    - assets/counting/


  fonts:
    - family: Vanilla Extract
      fonts:
        - asset: fonts/Vanilla_Extract/Vanilla-Extract-Regular.ttf

    - family: Bubble Bobble
      fonts:
        - asset: fonts/Bubble_Bobble/Bubble-Bobble.ttf