name: kids_preschool
description: A new Flutter project.

publish_to: 'none'


version: 1.2.3+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  flutter_tts: ^4.0.1
  sqflite: ^2.3.2
  rate_my_app: ^2.0.0
  audioplayers: ^5.2.1
  url_launcher: ^6.2.4
  auto_size_text: ^3.0.0
  share_plus: ^7.2.2
  floodfill_image: ^0.0.8
  google_mobile_ads: ^4.0.0
  app_tracking_transparency: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

cider:
  link_template:
    tag: https://github.com/example/project/releases/tag/%tag% # initial release link template
    diff: https://github.com/example/project/compare/%from%...%to% # subsequent releases link template
flutter:

  uses-material-design: true

  assets:
    - assets/database/
    - assets/icons/
    - assets/images/
    - assets/background/
    - assets/category/
    - assets/animation/
    - assets/time/
    - assets/sounds/
    - assets/animals/
    - assets/birds/
    - assets/education/
    - assets/fruits/
    - assets/money/
    - assets/shapes/
    - assets/vehicles/
    - assets/months/
    - assets/days/
    - assets/numbers/
    - assets/alphabets/
    - assets/alphabets_objects/
    - assets/colours/
    - assets/upper/
    - assets/lower/
    - assets/counting/


  fonts:
    - family: Vanilla Extract
      fonts:
        - asset: fonts/Vanilla_Extract/Vanilla-Extract-Regular.ttf

    - family: Bubble Bobble
      fonts:
        - asset: fonts/Bubble_Bobble/Bubble-Bobble.ttf